#!/usr/bin/env node
/**
 * Emits src/design/themes.css from src/design/tokens.json.
 * Run: pnpm tokens   (also runs before `pnpm build`).
 * Never hand-edit the generated file; edit tokens.json.
 *
 * With --check it writes nothing and exits non-zero if the committed CSS is stale
 * or a theme breaks an invariant, so `pnpm check` catches drift in CI.
 *
 * Invariants enforced here (a theme that breaks one fails the build):
 *   1. every theme declares exactly the same colour / shape / fx keys
 *   2. every font key a theme names exists in `fonts`
 *   3. a theme's own `series` (when present) has 8 valid hexes
 *   4. ink, ink-2 and ink-3 each clear a contrast floor against bg-2, and each
 *      step of the ink scale is actually distinguishable from the one above it
 * The categorical series palettes are validated separately, against the dataviz
 * skill's validator — see `seriesNote` in tokens.json.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, "../src/design/tokens.json");
const out = resolve(here, "../src/design/themes.css");
const tokens = JSON.parse(readFileSync(src, "utf8"));
const check = process.argv.includes("--check");

/* ----------------------------------------------------------------- invariants */
const problems = [];
const ids = Object.keys(tokens.themes);
const ref = tokens.themes[tokens.defaultTheme];
const keysOf = (o) => Object.keys(o).sort().join(",");

const HEX = /^#[0-9a-fA-F]{6}$/;
const srgbToLinear = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
function relLum(hex) {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255).map(srgbToLinear);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
function contrast(a, b) {
  const [hi, lo] = [relLum(a), relLum(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}
/** Ink floors: primary must be comfortably readable, muted must still be legible. */
const INK_FLOOR = { ink: 7, "ink-2": 4.5, "ink-3": 2.6 };
/** Consecutive ink steps must differ enough to read as a hierarchy. */
const INK_STEP = 1.25;

for (const id of ids) {
  const t = tokens.themes[id];
  const at = (m) => problems.push(`${id}: ${m}`);

  if (keysOf(t.color) !== keysOf(ref.color)) at(`colour keys differ from "${tokens.defaultTheme}"`);
  if (keysOf(t.shape) !== keysOf(ref.shape)) at(`shape keys differ from "${tokens.defaultTheme}"`);
  if (keysOf(t.fx) !== keysOf(ref.fx)) at(`fx keys differ from "${tokens.defaultTheme}"`);

  for (const slot of ["ui", "data", "read"]) {
    if (!tokens.fonts[t.fonts[slot]]) at(`fonts.${slot} = "${t.fonts[slot]}" is not a known font stack`);
  }
  if (t.series) {
    if (t.series.length !== 8) at(`series has ${t.series.length} entries, expected 8`);
    const bad = t.series.filter((h) => !HEX.test(h));
    if (bad.length) at(`series has invalid hex value(s): ${bad.join(", ")}`);
  }
  if (!["light", "dark"].includes(t.scheme)) at(`scheme "${t.scheme}" is not light or dark`);

  const surface = t.color["bg-2"];
  if (HEX.test(surface ?? "")) {
    for (const [role, floor] of Object.entries(INK_FLOOR)) {
      const c = t.color[role];
      if (!HEX.test(c ?? "")) continue;
      const ratio = contrast(c, surface);
      if (ratio < floor) at(`${role} ${c} on bg-2 ${surface} is ${ratio.toFixed(2)}:1, below ${floor}:1`);
    }
    const steps = ["ink", "ink-2", "ink-3"];
    for (let i = 0; i < steps.length - 1; i++) {
      const [a, b] = [t.color[steps[i]], t.color[steps[i + 1]]];
      if (!HEX.test(a ?? "") || !HEX.test(b ?? "")) continue;
      const sep = contrast(a, surface) / contrast(b, surface);
      if (sep < INK_STEP) {
        at(`${steps[i]} and ${steps[i + 1]} are only ${sep.toFixed(2)}× apart on bg-2 — no visible hierarchy`);
      }
    }
  }
}

if (problems.length) {
  console.error("tokens.json failed validation:\n" + problems.map((p) => `  ✗ ${p}`).join("\n"));
  process.exit(1);
}

/* -------------------------------------------------------------------- emitter */
const lines = [];
lines.push(`/* GENERATED by scripts/tokens-to-css.mjs from src/design/tokens.json — do not edit. */`);
lines.push(``);

function block(selector, theme) {
  const rows = [];
  rows.push(`  color-scheme: ${theme.scheme};`);
  for (const [k, v] of Object.entries(theme.color)) rows.push(`  --${k}: ${v};`);
  rows.push(`  --font-ui: ${tokens.fonts[theme.fonts.ui]};`);
  rows.push(`  --font-data: ${tokens.fonts[theme.fonts.data]};`);
  rows.push(`  --font-read: ${tokens.fonts[theme.fonts.read]};`);
  rows.push(`  --radius: ${theme.shape.radius};`);
  rows.push(`  --density: ${theme.shape.density};`);
  for (const [k, v] of Object.entries(theme.fx)) rows.push(`  --fx-${k}: ${v};`);
  // A theme's own palette wins; the scheme-level list is the fallback.
  const series = theme.series ?? tokens.series[theme.scheme];
  series.forEach((hex, i) => rows.push(`  --series-${i + 1}: ${hex};`));
  return `${selector} {\n${rows.join("\n")}\n}`;
}

const def = tokens.defaultTheme;
lines.push(block(`:root, [data-theme="${def}"]`, tokens.themes[def]));
for (const [id, theme] of Object.entries(tokens.themes)) {
  if (id === def) continue;
  lines.push(``);
  lines.push(block(`[data-theme="${id}"]`, theme));
}
lines.push(``);
const css = lines.join("\n");

if (check) {
  let current = "";
  try {
    current = readFileSync(out, "utf8");
  } catch {}
  if (current !== css) {
    console.error("themes.css is out of date — run `pnpm tokens` and commit the result.");
    process.exit(1);
  }
  console.log(`themes.css is up to date (${ids.length} themes)`);
} else {
  writeFileSync(out, css);
  console.log(`themes.css written (${ids.length} themes)`);
}
