#!/usr/bin/env node
/**
 * Emits src/design/themes.css from src/design/tokens.json.
 * Run: pnpm tokens   (also runs before `pnpm build`).
 * Never hand-edit the generated file; edit tokens.json.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, "../src/design/tokens.json");
const out = resolve(here, "../src/design/themes.css");
const tokens = JSON.parse(readFileSync(src, "utf8"));

const lines = [];
lines.push(`/* GENERATED by scripts/tokens-to-css.mjs from src/design/tokens.json — do not edit. */`);
lines.push(``);

function block(selector, theme) {
  const rows = [];
  rows.push(`  color-scheme: ${theme.scheme};`);
  for (const [k, v] of Object.entries(theme.color)) rows.push(`  --${k}: ${v};`);
  rows.push(`  --font-ui: ${tokens.fonts[theme.fonts.ui]};`);
  rows.push(`  --font-data: ${tokens.fonts[theme.fonts.data]};`);
  rows.push(`  --font-read: ${tokens.fonts[theme.fonts.read]};`);
  rows.push(`  --radius: ${theme.shape.radius};`);
  rows.push(`  --density: ${theme.shape.density};`);
  rows.push(`  --fx-scanlines: ${theme.fx.scanlines};`);
  rows.push(`  --fx-vignette: ${theme.fx.vignette};`);
  rows.push(`  --fx-bezel: ${theme.fx.bezel};`);
  const series = tokens.series[theme.scheme];
  series.forEach((hex, i) => rows.push(`  --series-${i + 1}: ${hex};`));
  return `${selector} {\n${rows.join("\n")}\n}`;
}

const def = tokens.defaultTheme;
lines.push(block(`:root, [data-theme="${def}"]`, tokens.themes[def]));
for (const [id, theme] of Object.entries(tokens.themes)) {
  if (id === def) continue;
  lines.push(``);
  lines.push(block(`[data-theme="${id}"]`, theme));
}
lines.push(``);
writeFileSync(out, lines.join("\n"));
console.log(`themes.css written (${Object.keys(tokens.themes).length} themes)`);
